const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let projects=[],current=null,items=[];
const API_URL='https://script.google.com/macros/s/AKfycbzKdXw6oc-LeZixABXiwYndrOAjB9WDPuLSfYcsBvCNsFwZfvEaNUpqoMh_dlTwn15_/exec';
let accessPassword='';
const stages=[
['Engineer onboarding','NAB reported','Standard access and secure developer environment are provisioned so engineers can work quickly without manual friction.'],
['Choose a quickstart','NAB reported','Start from a reusable, supported application pattern with logging, security and cloud foundations included.'],
['Build the feature','NAB reported','Write the service change and tests using standardised engineering languages and practices.'],
['Infrastructure as code','NAB reported','Describe cloud resources as versioned Terraform code rather than manual console changes.'],
['Controlled infrastructure deploy','NAB reported','Terraform Enterprise plans the intended change and applies only approved workspaces.'],
['Compliance as code','NAB reported','Sentinel policies automatically reject non-compliant infrastructure, such as missing required controls.'],
['Peer review & intent','NAB reported','A pull request, linked delivery intent and peer approval form an auditable change record.'],
['Continuous integration','NAB reported','A reusable Jenkins Templating Engine pipeline builds, tests and scans the change.'],
['Promotion through environments','NAB reported','The validated artifact follows a consistent route through development, test and production controls.'],
['Controlled release','Industry pattern','Feature flags or a canary rollout expose the production change gradually while teams monitor safety signals.'],
['Innersource improvement','NAB reported','Useful shared modules and patterns are contributed back for other delivery teams to reuse.'],
['Learn and operate','NAB reported','Cloud Guild learning, multi-cloud standards and AI-assisted maintenance strengthen the operating model.']];
function api(action,data={}){if(!accessPassword)throw Error('Enter the web-app password to continue.');return fetch(API_URL,{method:'POST',body:JSON.stringify({action,password:accessPassword,...data})}).then(r=>r.json()).then(x=>{if(!x.ok)throw Error(x.error||'Request failed');return x})}
function askForPassword(){const value=window.prompt('Enter the Banking Portfolio Desk access password:');accessPassword=value||'';}
function nav(page){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$$('.page').forEach(x=>x.classList.toggle('show',x.id===page));$('#pageTitle').textContent=page==='portfolio'?'Portfolio overview':page==='project'?'Project workspace':page==='reference'?'Cloud delivery reference':'Settings';$('#newProject').style.visibility=page==='portfolio'?'visible':'hidden'}
function renderPortfolio(){const total=projects.length,on=projects.filter(p=>p.status==='On track').length,risk=projects.filter(p=>p.health==='Amber'||p.health==='Red').length,done=projects.filter(p=>p.status==='Complete').length;$('#stats').innerHTML=[['Total projects',total],['On track',on],['Need attention',risk],['Completed',done]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#projectRows').innerHTML=projects.length?projects.map(p=>`<tr><td><span class="project-link" data-id="${p.id}">${esc(p.name)}</span><br><small>${esc(p.owner||'No owner')}</small></td><td>${esc(p.framework)}</td><td>${esc(p.phase)}</td><td><span class="badge health-${p.health}">${esc(p.health)}</span></td><td><div class="bar"><i style="width:${p.progress}%"></i></div> ${p.progress}%</td><td>${esc(p.nextStep||'—')}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No projects yet. Create your first delivery brief.</td></tr>';$$('.project-link').forEach(x=>x.onclick=()=>openProject(x.dataset.id));}
async function load(){try{projects=(await api('portfolio')).projects;renderPortfolio()}catch(e){$('#projectRows').innerHTML=`<tr><td colspan="6" class="empty">${esc(e.message)}</td></tr>`}}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function openProject(id){current=projects.find(p=>p.id===id)||null;items=[];if(id){try{const d=await api('project',{id});current=d.project;items=current.items||[]}catch(e){alert(e.message);return}}$('#emptyProject').hidden=true;$('#projectWorkspace').hidden=false;['name','framework','phase','status','health','owner','sponsor','startDate','targetDate','progress','requirements','nextStep','dependencies','risks'].forEach(k=>$('#'+k).value=current?.[k]??(k==='framework'?'Hybrid':k==='phase'?'Discovery':k==='health'?'Green':k==='progress'?0:''));$('#projectId').textContent=current?.id||'New project';$('#progressValue').textContent=$('#progress').value+'%';renderItems();nav('project')}
function renderItems(){const box=$('#items');box.innerHTML='';items.forEach((x,i)=>{const n=$('#itemTemplate').content.cloneNode(true);const e=n.querySelector('.item');e.querySelector('.itemType').value=x.type||'Risk';e.querySelector('.itemTitle').value=x.title||'';e.querySelector('.itemOwner').value=x.owner||'';e.querySelector('.itemDue').value=x.dueDate||'';e.querySelector('.itemStatus').value=x.status||'Open';e.querySelector('.remove').onclick=()=>{items.splice(i,1);renderItems()};box.append(n)})}
function readItems(){return $$('.item').map(e=>({type:e.querySelector('.itemType').value,title:e.querySelector('.itemTitle').value,owner:e.querySelector('.itemOwner').value,dueDate:e.querySelector('.itemDue').value,status:e.querySelector('.itemStatus').value,description:'',impact:'',likelihood:''})).filter(x=>x.title)}
async function save(){const p={id:current?.id};['name','framework','phase','status','health','owner','sponsor','startDate','targetDate','progress','requirements','nextStep','dependencies','risks'].forEach(k=>p[k]=$('#'+k).value);try{const r=await api('saveProject',{project:p});current={...p,id:r.id};items=readItems();await api('saveItems',{id:r.id,items});await load();$('#projectId').textContent=r.id;alert('Project saved to Google Sheets.')}catch(e){alert(e.message)}}
async function ai(kind){const brief={name:$('#name').value,framework:$('#framework').value,phase:$('#phase').value,requirements:$('#requirements').value,risks:$('#risks').value};const ask={requirements:'Draft concise, testable business and non-functional requirements plus acceptance criteria.',risks:'Identify banking-domain delivery, security, regulatory, operational and dependency risks. Give practical mitigations.',next:'Recommend the three highest-value next delivery actions, with a proposed owner role.'}[kind];$('#aiOutput').textContent='Thinking…';try{$('#aiOutput').textContent=(await api('ai',{prompt:ask,project:brief})).text}catch(e){$('#aiOutput').textContent='AI request failed: '+e.message}}
function renderFlow(){$('#flow').innerHTML=stages.map((s,i)=>`<details class="stage" ${i===0?'open':''}><summary><span class="number">${i+1}</span>${s[0]}<span class="tag">${s[1]}</span></summary><p>${s[2]}</p><ul><li>Capture the change and its evidence in the delivery record.</li><li>Use automated controls and peer review appropriate to the change.</li><li>Monitor outcomes, resolve exceptions, and feed reusable learning back.</li></ul></details>`).join('')}
$$('.nav').forEach(x=>x.onclick=()=>nav(x.dataset.page));$('#newProject').onclick=()=>openProject();$('#refresh').onclick=load;$('#saveProject').onclick=save;$('#addItem').onclick=()=>{items.push({type:'Risk',status:'Open'});renderItems()};$('#progress').oninput=e=>$('#progressValue').textContent=e.target.value+'%';$$('.aiAction').forEach(x=>x.onclick=()=>ai(x.dataset.prompt));$('#changePassword').onclick=()=>{askForPassword();load()};renderFlow();askForPassword();load();
