const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let projects=[],current=null,items=[];
const API_URL='https://script.google.com/macros/s/AKfycbzKdXw6oc-LeZixABXiwYndrOAjB9WDPuLSfYcsBvCNsFwZfvEaNUpqoMh_dlTwn15_/exec';
let accessPassword='';
const stages=[
['Engineer onboarding','Reference practice','Standard access and a secure developer environment are provisioned so engineers can work quickly without manual friction.'],
['Choose a quickstart','Reference practice','Start from a reusable, supported application pattern with logging, security and cloud foundations included.'],
['Build the feature','Reference practice','Write the service change and tests using standardised engineering languages and practices.'],
['Infrastructure as code','Reference practice','Describe cloud resources as versioned Terraform code rather than manual console changes.'],
['Controlled infrastructure deploy','Reference practice','Plan the intended change and apply it only to approved workspaces.'],
['Compliance as code','Reference practice','Automated policies reject non-compliant infrastructure, such as missing required controls.'],
['Peer review & intent','Reference practice','A pull request, linked delivery intent and peer approval form an auditable change record.'],
['Continuous integration','Reference practice','A reusable pipeline builds, tests and scans the change.'],
['Promotion through environments','Reference practice','The validated artifact follows a consistent route through development, test and production controls.'],
['Controlled release','Industry pattern','Feature flags or a canary rollout expose the production change gradually while teams monitor safety signals.'],
['Innersource improvement','Reference practice','Useful shared modules and patterns are contributed back for other delivery teams to reuse.'],
['Learn and operate','Reference practice','Shared learning, cloud standards and AI-assisted maintenance strengthen the operating model.']];
function api(action,data={}){if(!accessPassword)throw Error('Enter the web-app password to continue.');return fetch(API_URL,{method:'POST',body:JSON.stringify({action,password:accessPassword,...data})}).then(r=>r.json()).then(x=>{if(!x.ok)throw Error(x.error||'Request failed');return x})}
function askForPassword(){const value=window.prompt('Enter the Trailhead Portfolio access password:');accessPassword=value||'';}
function nav(page){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$$('.page').forEach(x=>x.classList.toggle('show',x.id===page));$('#pageTitle').textContent=page==='portfolio'?'Portfolio overview':page==='project'?'Project workspace':page==='reference'?'Cloud delivery reference':'Settings';$('#newProject').style.visibility=page==='portfolio'?'visible':'hidden'}
function renderPortfolio(){const total=projects.length,on=projects.filter(p=>p.status==='On track').length,risk=projects.filter(p=>p.health==='Amber'||p.health==='Red').length,done=projects.filter(p=>p.status==='Complete').length;$('#stats').innerHTML=[['Total projects',total],['On track',on],['Need attention',risk],['Completed',done]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#projectRows').innerHTML=projects.length?projects.map(p=>{const overdue=p.targetDate&&p.targetDate<todayStr()&&Number(p.progress)<100;return `<tr><td><span class="project-link" data-id="${p.id}">${esc(p.name)}</span><br><small>${esc(p.owner||'No owner')}</small></td><td>${esc(p.framework)}</td><td>${esc(p.phase)}</td><td><span class="badge health-${p.health}">${esc(p.health)}</span>${overdue?' <span class="badge health-Red">Overdue</span>':''}</td><td><div class="bar"><i style="width:${p.progress}%"></i></div> ${p.progress}%</td><td>${esc(p.nextStep||'—')}</td></tr>`}).join(''):'<tr><td colspan="6" class="empty">No projects yet. Create your first delivery brief.</td></tr>';$$('.project-link').forEach(x=>x.onclick=()=>openProject(x.dataset.id));}
async function load(){try{projects=(await api('portfolio')).projects;renderPortfolio()}catch(e){$('#projectRows').innerHTML=`<tr><td colspan="6" class="empty">${esc(e.message)}</td></tr>`}}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function nextTaskNo(){const n=items.filter(x=>x.type==='Task').map(x=>parseInt((x.taskNo||'T0').slice(1))||0);return 'T'+String((n.length?Math.max(...n):0)+1).padStart(3,'0')}
function isBlocked(task){return (task.dependsOn||[]).some(no=>{const d=items.find(x=>x.type==='Task'&&x.taskNo===no);return d&&d.status!=='Done'})}
const TASK_STATUSES=['To do','In progress','Done'];
function normStatus(s){return TASK_STATUSES.includes(s)?s:(s==='Closed'?'Done':'To do')}
function taskSortKey(t){return parseInt((t.taskNo||'T0').slice(1))||0}
function todayStr(){return new Date().toISOString().slice(0,10)}
function taskOverdue(t){return !!(t.dueDate&&t.status!=='Done'&&t.dueDate<todayStr())}
function updateHealthHint(tasks){const hint=$('#healthHint');if(!hint)return;const anyBlocked=tasks.some(t=>t.status!=='Done'&&isBlocked(t));const anyOverdueTask=tasks.some(taskOverdue);const target=$('#targetDate').value;const projectOverdue=!!(target&&target<todayStr()&&Number($('#progress').value)<100);let suggestion=null;if(projectOverdue||anyOverdueTask)suggestion='Red';else if(anyBlocked)suggestion='Amber';const cur=$('#health').value;hint.textContent=(suggestion&&suggestion!==cur)?`Suggested: ${suggestion} — doesn't match current selection, review if this reflects reality`:''}
function syncProgressAndNextStep(tasks){const progressEl=$('#progress'),labelEl=$('#progressValue'),nextEl=$('#nextStep');if(tasks.length){const totalEffort=tasks.reduce((s,t)=>s+(Number(t.leadTimeDays)||0),0);let pct;if(totalEffort>0){const doneEffort=tasks.filter(t=>t.status==='Done').reduce((s,t)=>s+(Number(t.leadTimeDays)||0),0);pct=Math.round(doneEffort/totalEffort*100)}else{const doneCount=tasks.filter(t=>t.status==='Done').length;pct=Math.round(doneCount/tasks.length*100)}progressEl.value=pct;progressEl.disabled=true;labelEl.textContent=pct+'% (auto'+(totalEffort>0?', effort-weighted':'')+')';const open_=tasks.filter(t=>t.status!=='Done').map(t=>({t,overdue:taskOverdue(t),blocked:isBlocked(t)}));let next='All tasks complete';if(open_.length){const score=x=>(x.overdue?0:2)+(x.blocked?1:0);open_.sort((a,b)=>score(a)-score(b)||(a.t.dueDate||'9999-99-99').localeCompare(b.t.dueDate||'9999-99-99')||taskSortKey(a.t)-taskSortKey(b.t));const pick=open_[0];next=`${pick.t.taskNo} — ${pick.t.title}`+(pick.overdue?' (overdue)':'')+(pick.blocked?' (blocked)':'')}nextEl.value=next;nextEl.readOnly=true}else{progressEl.disabled=false;labelEl.textContent=progressEl.value+'%';nextEl.readOnly=false}updateHealthHint(tasks)}
const NAV_TOOLTIPS={portfolio:'View all projects as a program-level portfolio, the way a PMO tracks a book of work.',project:'Open the delivery workspace for one project: brief, RAID log, and task backlog.',reference:'NAB-style cloud feature delivery pipeline — reference practice for engineer-to-production flow.',settings:'Manage backend connection and access to this workbook.'};
const TOOLTIPS={
  SAFe:{
    newProject:'Start a new Value Stream / ART initiative record in the portfolio.',
    refresh:'Reload the Program Board snapshot for this PI from the Google Sheets backend.',
    saveProject:'Commit this update to the Sheet — treat it as your Program Board / PI tracking source of truth.',
    addItem:'Log a new Risk, Assumption, Issue or Dependency for the ART\'s risk-and-impediment backlog (ROAM it at the next Scrum of Scrums).',
    changePassword:'Rotate the shared access credential guarding this ART\'s workbook.',
    addTask:'Add a story to this epic\'s backlog for the current Program Increment.',
    consult:'Ask an AI Scrum-Master-style consultant how to slice, size and unblock this story before the next PI Planning.',
    remove:'Remove this story from the backlog. If already saved, this won\'t rewrite team velocity history.',
    itemRemove:'Remove this RAID entry from the ART\'s risk-and-impediment backlog.',
    ai:{
      requirements:'Draft user-story-style requirements with acceptance criteria, ready for backlog refinement.',
      risks:'Surface risks and impediments typical of a SAFe increment, for the ART\'s ROAM board.',
      next:'Recommend the top backlog items to pull into the next Sprint or PI.'
    }
  },
  Hybrid:{
    newProject:'Start a new delivery record / BRD-tracked initiative in the portfolio.',
    refresh:'Reload the portfolio\'s latest status from the Google Sheets backend (your system of record).',
    saveProject:'Commit this update to the Sheet — treat it as your BRD / status-report source of truth for bank change governance.',
    addItem:'Log a new RAID entry (Risk, Assumption, Issue, Dependency) for the governance / steering pack.',
    changePassword:'Rotate the shared access credential guarding this workbook.',
    addTask:'Add a task to this project\'s work breakdown structure (WBS).',
    consult:'Ask an AI delivery-manager-style consultant for sub-steps, stakeholders and evidence needed to close this task under bank change-control practice.',
    remove:'Remove this task from the work breakdown structure.',
    itemRemove:'Remove this RAID entry from the governance / steering pack.',
    ai:{
      requirements:'Draft BRD-style business and non-functional requirements with acceptance criteria.',
      risks:'Identify delivery, regulatory and operational risks typical of a bank change request, for the RAID log.',
      next:'Recommend the next actions a Delivery Lead / TPM should take before the next steering update.'
    }
  }
};
function fw(){const v=current?.framework||$('#framework')?.value;return v==='SAFe'?'SAFe':'Hybrid'}
function applyStaticTooltips(){const T=TOOLTIPS[fw()];$('#newProject')?.setAttribute('title',T.newProject);$('#refresh')?.setAttribute('title',T.refresh);$('#saveProject')?.setAttribute('title',T.saveProject);$('#addItem')?.setAttribute('title',T.addItem);$('#changePassword')?.setAttribute('title',T.changePassword);$('#addTaskBtn')?.setAttribute('title',T.addTask);$$('.aiAction').forEach(x=>x.setAttribute('title',T.ai[x.dataset.prompt]||''));$$('.nav').forEach(x=>x.setAttribute('title',NAV_TOOLTIPS[x.dataset.page]||''))}
function markDirty(){dirty=true;updateDirtyIndicator()}
function updateDirtyIndicator(){const el=$('#dirtyFlag');if(el)el.style.display=dirty?'inline-block':'none'}
function setAIBusy(b){$$('.aiAction').forEach(x=>x.disabled=b);$$('.consult-task').forEach(x=>x.disabled=b)}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
async function openProject(id){current=projects.find(p=>p.id===id)||null;items=[];if(id){try{const d=await api('project',{id});current=d.project;items=current.items||[]}catch(e){alert(e.message);return}}$('#emptyProject').hidden=true;$('#projectWorkspace').hidden=false;['name','framework','phase','status','health','owner','sponsor','startDate','targetDate','progress','requirements','nextStep','dependencies','risks'].forEach(k=>$('#'+k).value=current?.[k]??(k==='framework'?'Hybrid':k==='phase'?'Discovery':k==='health'?'Green':k==='progress'?0:''));$('#projectId').textContent=current?.id||'New project';$('#progressValue').textContent=$('#progress').value+'%';applyStaticTooltips();renderItems();renderTasks();dirty=false;updateDirtyIndicator();nav('project')}
function renderItems(){const T=TOOLTIPS[fw()];const box=$('#items');box.innerHTML='';items.forEach((x,i)=>{if(x.type==='Task')return;const n=$('#itemTemplate').content.cloneNode(true);const e=n.querySelector('.item');e.querySelector('.itemType').value=x.type||'Risk';e.querySelector('.itemTitle').value=x.title||'';e.querySelector('.itemOwner').value=x.owner||'';e.querySelector('.itemDue').value=x.dueDate||'';e.querySelector('.itemStatus').value=x.status||'Open';const rm=e.querySelector('.remove');rm.title=T.itemRemove;rm.onclick=()=>{items.splice(i,1);renderItems();renderTasks()};box.append(n)})}
function renderTasks(){const T=TOOLTIPS[fw()];const tasks=items.filter(x=>x.type==='Task');tasks.forEach(t=>t.status=normStatus(t.status));const doneCount=tasks.filter(t=>t.status==='Done').length;$('#taskCount').textContent=tasks.length?`${tasks.length-doneCount} open · ${tasks.length} total`:'No tasks yet';$('#taskDependsOn').innerHTML=tasks.map(t=>`<option value="${t.taskNo}">${esc(t.taskNo)} — ${esc(t.title)}</option>`).join('');$('#taskList').innerHTML=tasks.length?tasks.map(task=>{const itemIndex=items.indexOf(task),blocked=task.status!=='Done'&&isBlocked(task),overdue=taskOverdue(task);const deps=(task.dependsOn||[]).length?`<span class="dep-tag">depends on ${task.dependsOn.join(', ')}</span>`:'';const lead=task.leadTimeDays?`<span class="lead-tag">${task.leadTimeDays}d</span>`:'';const owner=task.owner?`<span class="owner-tag">${esc(task.owner)}</span>`:'';const due=task.dueDate?`<span class="due-tag ${overdue?'overdue':''}">${overdue?'overdue ':'due '}${esc(task.dueDate)}</span>`:'';const statusCtl=blocked?`<select class="task-status" disabled title="Locked until the dependency above is Done"><option>Blocked</option></select>`:`<select class="task-status" data-status="${itemIndex}" title="Update this task's delivery status">${TASK_STATUSES.map(s=>`<option ${s===task.status?'selected':''}>${s}</option>`).join('')}</select>`;return `<div class="task ${task.status==='Done'?'done':''} ${blocked?'blocked':''} ${overdue?'overdue-row':''}"><span class="task-no">${esc(task.taskNo||'')}</span><span class="task-title">${esc(task.title)}</span>${owner}${lead}${due}${deps}${statusCtl}${blocked?'<span class="badge health-Amber">Blocked</span>':''}<button class="consult-task" data-consult="${itemIndex}" title="${esc(T.consult)}">Ask consultant</button><button class="remove-task" data-remove-task="${itemIndex}" title="${esc(T.remove)}" aria-label="Remove task">×</button></div>`}).join(''):'<p class="task-empty">Clear trail ahead — add the next useful action.</p>';$$('[data-status]').forEach(el=>el.onchange=()=>{items[Number(el.dataset.status)].status=el.value;markDirty();renderTasks()});$$('[data-remove-task]').forEach(el=>el.onclick=()=>{const i=Number(el.dataset.removeTask),removed=items[i];items.splice(i,1);if(removed?.taskNo)items.forEach(t=>{if(t.type==='Task'&&t.dependsOn)t.dependsOn=t.dependsOn.filter(no=>no!==removed.taskNo)});markDirty();renderTasks()});$$('[data-consult]').forEach(el=>el.onclick=()=>consultTask(Number(el.dataset.consult)));syncProgressAndNextStep(tasks)}
async function consultTask(i){if(aiBusy)return;const task=items[i];if(!task)return;const deps=(task.dependsOn||[]).map(no=>{const d=items.find(x=>x.type==='Task'&&x.taskNo===no);return d?`${no} (${d.title} — ${d.status})`:no}).join('; ')||'None';const blocked=isBlocked(task);const brief={name:$('#name').value,framework:$('#framework').value,phase:$('#phase').value,requirements:$('#requirements').value,risks:$('#risks').value};const prompt=`Act as a delivery consultant for one task inside a ${brief.framework||'Hybrid'} banking delivery project (delivery phase: ${brief.phase||'n/a'}).\n\nTask: ${task.taskNo} — ${task.title}\nOwner: ${task.owner||'Unassigned'}\nStatus: ${task.status}${blocked?' (currently blocked by an open dependency)':''}\nLead time: ${task.leadTimeDays||0} day(s)\nDue: ${task.dueDate||'not set'}${taskOverdue(task)?' (overdue)':''}\nDepends on: ${deps}\n\nBrainstorm everything useful to deliver this task well: the concrete sub-steps, likely blockers or risks specific to a bank/fintech context, who should be involved (roles, not names), what evidence or artifacts should be produced for audit/compliance, and how this fits the ${brief.framework||'Hybrid'} framework's ceremonies or governance. Be concise and structured with headers.`;const nav_=$('.nav[data-page="project"]');if(nav_)nav_.click();aiBusy=true;setAIBusy(true);$('#aiOutput').textContent=`Consulting on ${task.taskNo} — ${task.title}…`;$('#aiOutput').scrollIntoView({behavior:'smooth',block:'center'});try{const r=await api('ai',{prompt,project:brief});$('#aiOutput').textContent=`Consultant view — ${task.taskNo}: ${task.title}\n\n${r.text}`}catch(e){$('#aiOutput').textContent='AI request failed: '+e.message}finally{aiBusy=false;setAIBusy(false)}}
function readItems(){const tasks=items.filter(x=>x.type==='Task');const controls=$$('.item').map(e=>({type:e.querySelector('.itemType').value,title:e.querySelector('.itemTitle').value,owner:e.querySelector('.itemOwner').value,dueDate:e.querySelector('.itemDue').value,status:e.querySelector('.itemStatus').value,description:'',impact:'',likelihood:''})).filter(x=>x.title);return [...tasks,...controls]}
async function save(){const p={id:current?.id};['name','framework','phase','status','health','owner','sponsor','startDate','targetDate','progress','requirements','nextStep','dependencies','risks'].forEach(k=>p[k]=$('#'+k).value);if(!p.name.trim()){alert('Project name is required before saving.');$('#name').focus();return}try{const r=await api('saveProject',{project:p});current={...p,id:r.id};items=readItems();await api('saveItems',{id:r.id,items});await load();$('#projectId').textContent=r.id;dirty=false;updateDirtyIndicator();alert('Project saved to Google Sheets.')}catch(e){alert(e.message)}}
async function ai(kind){if(aiBusy)return;const brief={name:$('#name').value,framework:$('#framework').value,phase:$('#phase').value,requirements:$('#requirements').value,risks:$('#risks').value};const ask={requirements:'Draft concise, testable business and non-functional requirements plus acceptance criteria.',risks:'Identify banking-domain delivery, security, regulatory, operational and dependency risks. Give practical mitigations.',next:'Recommend the three highest-value next delivery actions, with a proposed owner role.'}[kind];aiBusy=true;setAIBusy(true);$('#aiOutput').textContent='Thinking…';try{$('#aiOutput').textContent=(await api('ai',{prompt:ask,project:brief})).text}catch(e){$('#aiOutput').textContent='AI request failed: '+e.message}finally{aiBusy=false;setAIBusy(false)}}
function renderFlow(){$('#flow').innerHTML=stages.map((s,i)=>`<details class="stage" ${i===0?'open':''}><summary><span class="number">${i+1}</span>${s[0]}<span class="tag">${s[1]}</span></summary><p>${s[2]}</p><ul><li>Capture the change and its evidence in the delivery record.</li><li>Use automated controls and peer review appropriate to the change.</li><li>Monitor outcomes, resolve exceptions, and feed reusable learning back.</li></ul></details>`).join('')}
$$('.nav').forEach(x=>x.onclick=()=>nav(x.dataset.page));$('#newProject').onclick=()=>openProject();$('#refresh').onclick=load;$('#saveProject').onclick=save;$('#addItem').onclick=()=>{items.push({type:'Risk',status:'Open'});markDirty();renderItems()};$('#taskForm').onsubmit=e=>{e.preventDefault();const title=$('#taskText').value.trim();if(!title)return;const leadTimeDays=Number($('#taskLeadTime').value)||0;const owner=$('#taskOwner').value.trim();const dueDate=$('#taskDue').value;const dependsOn=[...$('#taskDependsOn').selectedOptions].map(o=>o.value);items.unshift({type:'Task',taskNo:nextTaskNo(),title,owner,leadTimeDays,dueDate,dependsOn,status:'To do'});$('#taskText').value='';$('#taskOwner').value='';$('#taskLeadTime').value='';$('#taskDue').value='';$('#taskDependsOn').selectedIndex=-1;markDirty();renderTasks()};$('#progress').oninput=e=>{if(!e.target.disabled)$('#progressValue').textContent=e.target.value+'%'};$$('.aiAction').forEach(x=>x.onclick=()=>ai(x.dataset.prompt));$('#changePassword').onclick=()=>{askForPassword();load()};$('#projectWorkspace').addEventListener('input',markDirty);$('#projectWorkspace').addEventListener('change',()=>{markDirty();updateHealthHint(items.filter(x=>x.type==='Task'))});$('#framework').addEventListener('change',()=>{applyStaticTooltips();renderTasks();renderItems()});applyStaticTooltips();renderFlow();askForPassword();load();
